```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment=NA,attr.source='.numberLines')

rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
```

```{r connect}

my_db <- RSQLite::dbConnect(RSQLite::SQLite(),"e-commerce.db")

```

### Customer

```{sql, connection = my_db}
--customer

CREATE TABLE IF NOT EXISTS customer(
  cust_id INT PRIMARY KEY,
  cust_reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cust_last_name VARCHAR (100) NOT NULL,
  cust_first_name VARCHAR (100),
  cust_email VARCHAR (100) UNIQUE NOT NULL,
  cust_password VARBINARY(100) NOT NULL, -- encrypted
  cust_phone INT (15) UNIQUE,
  cust_birth_date DATE,
  cust_street_address VARCHAR (255),
  cust_city VARCHAR (50),
  cust_zipcode VARCHAR (10),
  score INT, -- calculation on score
  mem_id INT,
  FOREIGN KEY (mem_id) REFERENCES membership(mem_id)
); 
```

```{sql, connection = my_db}
-- membership

CREATE TABLE IF NOT EXISTS membership(
  mem_id INT PRIMARY KEY,
  mem_name VARCHAR(10) CHECK (mem_type IN ('PLATINUM', 'GOLD', 'SILVER', 'BRONZE'))
);
```


```{sql, connection = my_db}
-- product

CREATE TABLE IF NOT EXISTS product(
  product_id INT PRIMARY KEY,
  product_name VARCHAR(100),
  brand_id INT,
  weight INT,
  selling_price INT,
  category_id INT,
  product_desc VARCHAR(250),
  FOREIGN KEY (brand_id) REFERENCES brand(brand_id),
  FOREIGN KEY (category_id) REFERENCES category(category_id)
);
```

```{sql, connection = my_db}
-- review

CREATE TABLE IF NOT EXISTS review(
  review_id INT PRIMARY KEY,
  product_id INT,
  cust_id INT,
  review_score INT CHECK (review_score BETWEEN 1 AND 5),
  review_description VARCHAR(255),
  FOREIGN KEY (product_id) REFERENCES product(product_id),
  FOREIGN KEY (cust_id) REFERENCES customer(cust_id)
);
```

```{sql, connection = my_db} 
-- stock

CREATE TABLE IF NOT EXISTS stock(
  sku INT PRIMARY KEY,
  product_id INT,
  stock_qty INT, -- substraction between what is bought and what is being sold 
  stocking_date DATE, --arrival date at the warehouse 
  shipping_date DATE,
  warehouse_id INT,
  FOREIGN KEY (product_id) REFERENCES product(product_id),
  FOREIGN KEY (warehouse_id) REFERENCES warehouse(warehouse_id)
);
```

```{sql, connection = my_db}
-- Brand

CREATE TABLE IF NOT EXISTS brand (
 brand_id INT PRIMARY KEY,  
 brand_name VARCHAR
); 
```

```{sql, connection = my_db}
-- Category
CREATE TABLE IF NOT EXISTS prod_category (
 prod_category_id INT PRIMARY KEY,  
 prod_category_name VARCHAR (50)
); 
```

```{sql, connection = my_db}
-- Customer delivery
CREATE TABLE IF NOT EXISTS cust_delivery (
 cust_delivery_id INT PRIMARY KEY,  
 delivery_company_id INT,
 FOREIGN KEY (delivery_company_id) REFERENCES delivery_company (delivery_company_id),
 status VARCHAR(10) CHECK (status IN ('In Transit', 'Pending', 'Delivered')),
 dispatched_date DATE,
 estimated_delivery_date DATE,
 delivery_date DATE
); 
```

```{sql, connection = my_db}
-- delivery_company
CREATE TABLE IF NOT EXISTS delivery_company (
 delivery_company_id INT PRIMARY KEY,  
 company_name CHAR (50),
 company_contact_no INT,
 account_no VARCHAR (30)
); 
```

```{sql, connection = my_db}
-- Voucher
CREATE TABLE IF NOT EXISTS voucher (
 voucher_id INT PRIMARY KEY,  
 redeemed_voucher INT, --amount redeemed
 voucher_exp_date DATE,
 voucher_amount INT -- redeemed amount
); 
```

```{sql, connection = my_db}
-- payment method
CREATE TABLE IF NOT EXISTS method (
 payment_method_id INT PRIMARY KEY,  
 method_type VARCHAR
); 
```


```{sql, connection = my_db}
-- customer order
CREATE TABLE IF NOT EXISTS cust_order (
 cust_order_id INT PRIMARY KEY,
 order_date DATE,
 total_amount INT,
 cust_id INT,
 FOREIGN KEY (cust_id) 
     REFERENCES customer (cust_id),
 cust_delivery_id INT,
 FOREIGN KEY (cust_delivery_id) 
    REFERENCES cust_delivery (cust_delivery_id)
); 
```





```{sql, connection = my_db}
-- Order_details
CREATE TABLE IF NOT EXISTS order_details (
 order_details_id INT PRIMARY KEY,
 order_id INT, 
  FOREIGN KEY (order_id)
   REFERENCES cust_order (order_id),
 cust_order_street_add VARCHAR (250),
 cust_order_city VARCHAR (200)
 cust_order_zipcode VARCHAR (50)
 cust_order_cost INT, --to customer
 cust_order_phone INT (11),
 quantity INT,
 item_number INT,
 FOREIGN KEY ('item_number')
    REFERENCES product ('item_number')
); 
```

```{sql, connection = my_db}
-- payment     --- we need to add total payment in this section?

CREATE TABLE IF NOT EXISTS payment (
 payment_id INT PRIMARY KEY,
 cust_order_id INT, 
  FOREIGN KEY ('cust_order_id')
   REFERENCES cust_order ('cust_order_id'),
  payment_method_id INT,
  FOREIGN KEY ('payment_method_id')
  REFERENCES method ('payment_method_id'),
  total_payment_amount INT,
 remaining_payment_amount INT, -- pay_rest amount
 voucher_used_amount INT
); 
```
  
### Supplier
```{sql, connection = my_db}
-- Supplier
CREATE TABLE supplier (
  supplier_id INT PRIMARY KEY,
  s_name VARCHAR(255),
  s_street_address VARCHAR(255),
  s_city VARCHAR(100),
  s_zipcode VARCHAR(20),
  s_rating INT,
  s_phone INT(11),
  s_email VARCHAR(255)
);
```

### Supplier contract
```{sql, connection = my_db}
-- Supplier contract
CREATE TABLE s_contract (
  po_id INT PRIMARY KEY,
  contract_date DATE,
  total_unit INT,
  unit_price DECIMAL(10, 2),
  total_price DECIMAL(12, 2) GENERATED ALWAYS AS (total_unit * unit_price) STORED, -- this would be the payment that we would be doing to the suppliers
  s_id INT,
  product_id INT,
  FOREIGN KEY (s_id) REFERENCES supplier(s_id),
  FOREIGN KEY (product_id) REFERENCES product(product_id)
);
```

### Supplier payment
```{sql, connection = my_db}
-- Supplier payment
CREATE TABLE s_payment (
  s_payment_id INT PRIMARY KEY,
  payment_date DATE,
  payment_status VARCHAR(50) CHECK (payment_status IN ('Pending', 'Completed')),
  paid_amount DECIMAL(12, 2),
  po_id INT,
  FOREIGN KEY (po_id) REFERENCES s_contract(po_id),
);
```


### Warehouse
```{sql, connection = my_db}
-- Warehouse 
CREATE TABLE 'warehouse' (
  w_id INT PRIMARY KEY,
  w_name VARCHAR(255),
  w_street_address VARCHAR(255),
  w_city VARCHAR(100),
  w_zipcode VARCHAR(20),
);
```

### Shelf
```{sql, connection = my_db}
-- shelf
CREATE TABLE shelf (
  sh_id INT PRIMARY KEY,
  sh_total_capacity INT,
  sh_current_occupancy INT,
  sh_current_remaining INT GENERATED ALWAYS AS (sh_total_capacity - sh_current_occupancy) STORED,
  w_id INT,
  FOREIGN KEY (w_id) REFERENCES warehouse(w_id)
);
```

### warehouse_delivery
```{sql, connection = my_db}
-- warehouse_deliver
CREATE TABLE wh_delivery (
  wh_delivery_id INT PRIMARY KEY,
  delivery_status VARCHAR(50) CHECK (status IN ('In Transit', 'Pending', 'Delivered')), --for warehouse
  dispatched_date DATE, --from suppliers
  estimated_delivery_date DATE, -- from suppliers to warehouse
  arrival_date DATE,-- warehouse arrival date
  w_id INT,
  po_id INT,
  delivery_company_id INT,
  FOREIGN KEY (w_id) REFERENCES warehouse(warehouse_id),
  FOREIGN KEY (po_id) REFERENCES purchase(po_id),
  FOREIGN KEY (delivery_company_id) REFERENCES delivery_company(delivery_company_id)
);
```


### promotion -- need to be discussed 
```{sql, connection = my_db}
-- Promotion
CREATE TABLE promotion (
  promo_type_id INT PRIMARY KEY,
  promo_type VARCHAR(50) UNIQUE
);
```

### product_promotion
```{sql, connection = my_db}
-- Product Promotion
CREATE TABLE product_promotion (
  prod_promo_id INT PRIMARY KEY,
  promo_name VARCHAR(255),
  start_date DATE,
  end_date DATE,
  status VARCHAR(50),
  discount_rate DECIMAL(5, 2),
  promo_type_id INT,
  product_id INT,
  FOREIGN KEY (promo_type_id) REFERENCES promotion(promo_type_id),
  FOREIGN KEY (product_id) REFERENCES product(product_id)
);
```

### brand_promotion
```{sql, connection = my_db}
-- Brand Promotion
CREATE TABLE brand_promotion (
  brand_promo_id INT PRIMARY KEY,
  promo_name VARCHAR(255),
  start_date DATE,
  end_date DATE,
  status VARCHAR(50),
  discount_rate DECIMAL(5, 2),
  promo_type_id INT,
  brand_id INT,
  FOREIGN KEY (promo_type_id) REFERENCES promotion(promo_type_id),
  FOREIGN KEY (brand_id) REFERENCES brand(brand_id)
);
```

### category_promotion
```{sql, connection = my_db}
-- Category Promotion
CREATE TABLE category_promotion (
  cat_promo_id INT PRIMARY KEY,
  promo_name VARCHAR(255),
  start_date DATE,
  end_date DATE,
  status VARCHAR(50),
  discount_rate DECIMAL(5, 2),
  promo_type_id INT,
  brand_id INT,
  FOREIGN KEY (promo_type_id) REFERENCES promotion(promo_type_id),
  FOREIGN KEY (category_id) REFERENCES product_category(category_id)
);
```

### membership_promotion
```{sql, connection = my_db}
-- Membership Promotion
CREATE TABLE membership_promotion (
  mem_promo_id INT PRIMARY KEY,
  promo_name VARCHAR(255),
  start_date DATE,
  end_date DATE,
  status VARCHAR(50),
  discount_rate DECIMAL(5, 2),
  promo_type_id INT,
  brand_id INT,
  FOREIGN KEY (promo_type_id) REFERENCES promotion(promo_type_id),
  FOREIGN KEY (mem_id) REFERENCES membership(mem_id)
);
```

### media_platfrom
```{sql, connection = my_db}
-- Media Platform
CREATE TABLE media_platform (
  media_id INT PRIMARY KEY,
  media_type VARCHAR(50),
  media_name VARCHAR(255)
);
```

### ad
```{sql, connection = my_db}
-- Ad
CREATE TABLE ad (
  ad_id INT PRIMARY KEY,
  ad_campaign VARCHAR(255),
  ad_group VARCHAR(255),
  ad_content VARCHAR(255),
  start_date DATE,
  end_date DATE,
  impression INT,
  click INT,
  cost DECIMAL(10, 2),
  action INT,
  cpc DECIMAL(10, 2),
  ctr DECIMAL(5, 2),
  cpa DECIMAL(10, 2),
  media_id INT,
  FOREIGN KEY (media_id) REFERENCES media_platform(media_id)
);

```
