library(readr)
library(RSQLite)
library(dplyr)

customer_data <- readr::read_csv("data_upload/customer.csv", col_types=cols()) %>% select(-1)
ad_data <- readr::read_csv("data_upload/ad.csv", col_types=cols()) %>% select(-1)
#warehouse_data <- readr::read_delim("data_upload/warehouse.csv", col_types=cols(), delim = ',')
#promotion_data <- readr::read_csv("data_upload/promotion.csv", col_types=cols())
product_data <- readr::read_csv("data_upload/product.csv", col_types=cols()) %>% select(-1)
order_data <- readr::read_csv("data_upload/order.csv")
sell_data <- readr::read_csv("data_upload/sell.csv")
supplier_data <- readr::read_csv("data_upload/supplier.csv", col_types=cols()) %>% select(-1)
#promote_data <- readr::read_csv("data_upload/promote.csv", col_types=cols()) %>% select(-1)
stock_data <- readr::read_csv("data_upload/stock.csv")

my_connection <- RSQLite::dbConnect(RSQLite::SQLite(),"e-commerce.db")

RSQLite::dbWriteTable(my_connection,"customer",customer_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection,"ad",ad_data, append = TRUE, row.names = FALSE)
#RSQLite::dbWriteTable(my_connection,"warehouse",warehouse_data, append = TRUE, row.names = FALSE)
#RSQLite::dbWriteTable(my_connection, "promotion", promotion_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection, "product", product_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection, "order", order_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection, "sell", sell_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection, "supplier", supplier_data, append = TRUE, row.names = FALSE)
#RSQLite::dbWriteTable(my_connection, "promote", promote_data, append = TRUE, row.names = FALSE)
RSQLite::dbWriteTable(my_connection, "stock", stock_data, append = TRUE, row.names = FALSE)
