library(readr)
library(RSQLite)

customer <- readr::read_csv("data_upload/customer.csv")

con <- dbConnect(RSQLite::SQLite(), dbname = "database/e-commerce.db")
dbWriteTable(con, "customer", customer, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ad", ad, append = TRUE, row.names = FALSE)
dbWriteTable(con, "warehouse", warehouse, append = TRUE, row.names = FALSE)
dbWriteTable(con, "promotion", promotion_data, append = TRUE, row.names = FALSE)
dbWriteTable(con, "product", product, append = TRUE, row.names = FALSE)
dbWriteTable(con, "order", order_data, append = TRUE, row.names = FALSE)
dbWriteTable(con, "sell", sell_data, append = TRUE, row.names = FALSE)
dbWriteTable(con, "supplier", supplier, append = TRUE, row.names = FALSE)
dbWriteTable(con, "promote", promote, append = TRUE, row.names = FALSE)
dbWriteTable(con, "stock", stock, append = TRUE, row.names = FALSE)
